### ISSUE TITLE
Please update installation instructions

### ISSUE THREAD

**Issue by alexeyev** [bigartm/visartm#10]
Hi, thanks for the cool instrument! 
I liked playing with the online demo a lot.

A few bugreports on installation instructions located here http://visartm.vdi.mipt.ru/docs/installation are below.

---

There is no such file
```
visartm/settings.py
```

In default settings file there is just sqlite config, so one has to add postgres into DATABASES him/herself.

To use the recommended postgres, one will also have to install psycopg2, which is not listed in the requirements.txt.

Having fixed all this, one runs 
```
python2 manage.py makemigrations
```
and gets
```
Traceback (most recent call last):
  File "manage.py", line 23, in <module>
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/usr/local/lib/python2.7/dist-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/usr/local/lib/python2.7/dist-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/myhomedirectory/visartm/visual/models.py", line 3, in <module>
    from models.models import ArtmModel, Topic, TopicInTopic
ImportError: No module named models
```

Is the current version in the repo up-to-date? Or should I use another branch for local installation?

Thanks!

**Comment by anticodeninja** [comment]
@alexeyev, thank you for feedback!

Yes, installation doc is a little bit obsolete: settings.py by default use sqlite database and you should install optional dependencies like psycopg2 to work with postresql database which is not described in installation doc.
I will update in the near future (also you are welcome to update it on your own).

And I'm not sure that visartm works with python 2, could you check your installation with python 3?
Last changes in "master" branch works fine for my local installation with python 3.

**Comment by alexeyev** [comment]
@anticodeninja thanks for quick response.

> you are welcome to update it on your own

I will try to make a pull request ASAP, though not today.

> could you check your installation with python 3

I'm not sure why I decided visartm is python2-only : ) Everything works fine with python3, thanks.
